version: "3"
services:
  pg_red:
     hostname: pg_red
     build: ./master
     ports:
         - "5445:5432"
     volumes:
         - pg_red_data:/var/lib/postgresql/data
         #- shared_tmp:/tmp
     environment:
         - POSTGRES_USER=optima
         - POSTGRES_PASSWORD=123456
         - POSTGRES_DB=postgres
         - PG_REP_USER=rep
         - PG_REP_PASSWORD=123456
         - WHOISTHIS=pg_red
     networks:
           - bridge-docker
     restart: always
  pg_green:
     hostname: pg_green
     build: ./slave
     depends_on:
         - pg_red
     ports:
         - "5446:5432"
     volumes:
         - pg_green_data:/var/lib/postgresql/data
         - shared_tmp:/tmp
     environment:
         - POSTGRES_USER=optima
         - POSTGRES_PASSWORD=123456
         - POSTGRES_DB=postgres
         - PG_REP_USER=rep
         - PG_REP_PASSWORD=123456
         - WHOISTHIS=pg_green
     networks:
            - bridge-docker
     restart: always
  pg_blue:
     hostname: pg_blue
     build: ./slave
     depends_on:
         - pg_red
     ports:
         - "5447:5432"
     volumes:
         - pg_blue_data:/var/lib/postgresql/data
         - shared_tmp:/tmp
     environment:
         - POSTGRES_USER=optima
         - POSTGRES_PASSWORD=123456
         - POSTGRES_DB=postgres
         - PG_REP_USER=rep
         - PG_REP_PASSWORD=123456
         - WHOISTHIS=pg_blue
     networks:
            - bridge-docker
     restart: always
  # WIWWO
  pgpool:
     hostname: pgpool1
     build: ./pgpool
     depends_on:
         - pg_red
         - pg_green
         - pg_blue
     ports:
         - "9999:9999"
     volumes:
         - shared_tmp:/tmp
     environment:
         - POSTGRES_USERNAME=optima
         - POSTGRES_PASSWORD=123456
         - PGPOOL_PARAMS_BACKEND_HOSTNAME0=pg_red
         - PGPOOL_PARAMS_BACKEND_HOSTNAME1=pg_green
         - PGPOOL_PARAMS_BACKEND_HOSTNAME2=pg_blue
         - PGPOOL_PARAMS_BACKEND_PORT0=5432
         - PGPOOL_PARAMS_BACKEND_PORT1=5432
         - PGPOOL_PARAMS_BACKEND_PORT2=5432
         - PGPOOL_PARAMS_SR_CHECK_PERIOD=10
         - PGPOOL_PARAMS_SR_CHECK_USER=rep
         - PGPOOL_PARAMS_SR_CHECK_PASSWORD=123456
         - PGPOOL_PARAMS_HEALTH_CHECK_PERIOD=2
         - PGPOOL_PARAMS_HEALTH_CHECK_USER=rep
         - PGPOOL_PARAMS_HEALTH_CHECK_PASSWORD=123456
         - PGPOOL_PARAMS_BACKEND_WEIGHT0=1
         - PGPOOL_PARAMS_BACKEND_WEIGHT1=1
         - PGPOOL_PARAMS_BACKEND_WEIGHT2=1
         - PGPOOL_PARAMS_MASTER_SLAVE_MODE=on
         - PGPOOL_PARAMS_LOAD_BALANCE_MODE=on
         # FAILOVER
         - PGPOOL_PARAMS_BACKEND_FLAG0='ALLOW_TO_FAILOVER'
         - PGPOOL_PARAMS_BACKEND_FLAG1='ALLOW_TO_FAILOVER'
         - PGPOOL_PARAMS_BACKEND_FLAG2='ALLOW_TO_FAILOVER'
         - PGPOOL_PARAMS_FAILOVER_ON_BACKEND_ERROR=ON
         - PGPOOL_PARAMS_FAILOVER_COMMAND="/failover.sh" %H
         - PGPOOL_PARAMS_FOLLOW_MASTER_COMMAND="/setup-slave.sh NEW_MASTER %H"
     networks:
         - bridge-docker
     restart: always
volumes:
  pg_red_data:
  pg_green_data:
  pg_blue_data:
  shared_tmp:
networks:
  bridge-docker: