version: "3"
services:
  pg_master_1:
     build: ./master
     ports:
         - "5445:5432"
     volumes:
         - mdata:/var/lib/postgresql/data
     environment:
         - POSTGRES_USER=optima
         - POSTGRES_PASSWORD=123456
         - POSTGRES_DB=postgres
         - PG_REP_USER=rep
         - PG_REP_PASSWORD=123456
     networks:
           - bridge-docker
     restart: always
  pg_slave_1:
     build: ./slave
     ports:
         - "5446:5432"
     volumes:
         - sdata:/var/lib/postgresql/data
     environment:
         - POSTGRES_USER=optima
         - POSTGRES_PASSWORD=123456
         - POSTGRES_DB=postgres
         - PG_REP_USER=rep
         - PG_REP_PASSWORD=123456
     networks:
            - bridge-docker
     restart: always
  # WIWWO
  pgpool:
     build: ./pgpool
     ports:
         - "9999:9999"
     environment:
         - POSTGRES_USERNAME=optima
         - POSTGRES_PASSWORD=123456
         - PGPOOL_PARAMS_BACKEND_HOSTNAME0=pg_master_1
         - PGPOOL_PARAMS_BACKEND_HOSTNAME1=pg_slave_1
         - PGPOOL_PARAMS_BACKEND_PORT0=5432
         - PGPOOL_PARAMS_BACKEND_PORT1=5432
         - PGPOOL_PARAMS_SR_CHECK_PERIOD=10
         - PGPOOL_PARAMS_SR_CHECK_USER=rep
         - PGPOOL_PARAMS_SR_CHECK_PASSWORD=123456
         - PGPOOL_PARAMS_HEALTH_CHECK_PERIOD=10
         - PGPOOL_PARAMS_HEALTH_CHECK_USER=rep
         - PGPOOL_PARAMS_HEALTH_CHECK_PASSWORD=123456
         - PGPOOL_PARAMS_BACKEND_WEIGHT0=0.1
         - PGPOOL_PARAMS_BACKEND_WEIGHT1=0.9
         - PGPOOL_PARAMS_MASTER_SLAVE_MODE=on
     networks:
         - bridge-docker
     restart: always
volumes:
  mdata:
  sdata:
networks:
  bridge-docker:
    external:
      name: bridge-docker
